---
abstract: 'use DateTime without needing to call constructors'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
  - 'TOBYINK <tobyink@cpan.org>'
build_requires:
  Test::More: '0.61'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.016, CPAN::Meta::Converter version 2.140640'
keywords:
  - Date
  - DateTime
  - DateTimeX
  - Perl
  - Time
  - constant
  - overload
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DateTimeX-Auto
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  DateTimeX::Auto:
    file: lib/DateTimeX/Auto.pm
    version: '0.008'
  DateTimeX::Auto::DateTime:
    file: lib/DateTimeX/Auto.pm
    version: '0.008'
  DateTimeX::Auto::Duration:
    file: lib/DateTimeX/Auto.pm
    version: '0.008'
requires:
  DateTime: '0'
  DateTime::Duration: '0'
  DateTime::Format::Strptime: '0'
  Exporter::Shiny: '0'
  UNIVERSAL::ref: '0'
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/DateTimeX-Auto/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=DateTimeX-Auto
  homepage: https://metacpan.org/release/DateTimeX-Auto
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-datetimex-auto.git
version: '0.008'
